services:
  rest-api:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - config.env
  
  postgres:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - config.env

volumes:
  pgdata:
    driver: local